package engine

import (
	"fmt"
	"os"
	"strings"
	"time"

	gitpkg "github.com/elpic/blueprint/internal/git"
	handlerskg "github.com/elpic/blueprint/internal/handlers"
	"github.com/elpic/blueprint/internal/parser"
	"github.com/elpic/blueprint/internal/ui"
)

// Export generates a shell script from a blueprint file.
// format is "bash" or "sh". output is "" for stdout or a file path.
func Export(file string, format string, output string, preferSSH bool) {
	handlerskg.RegisterExportFuncs()
	if preferSSH {
		file = gitpkg.ExpandShorthandSSH(file)
	} else {
		file = gitpkg.ExpandShorthand(file)
	}

	setupPath, _, cleanup, err := resolveBlueprintFile(file, false, preferSSH)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", ui.FormatError(fmt.Sprintf("Error: %v", err)))
		os.Exit(1)
	}
	defer cleanup()

	rules, err := parser.ParseFile(setupPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", ui.FormatError(fmt.Sprintf("Parse error: %v", err)))
		os.Exit(1)
	}

	currentOS := getOSName()
	filtered := filterRulesByOS(rules)

	sorted, err := resolveDependencies(filtered)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", ui.FormatError(err.Error()))
		os.Exit(1)
	}

	script := buildScript(sorted, format, currentOS, file)

	if output != "" {
		if err := os.WriteFile(output, []byte(script), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "%s\n", ui.FormatError(fmt.Sprintf("Error writing file: %v", err)))
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "%s\n", ui.FormatSuccess(fmt.Sprintf("Exported to %s", output)))
	} else {
		fmt.Print(script)
	}
}

func buildScript(rules []parser.Rule, format, osName, blueprintFile string) string {
	var b strings.Builder

	writeHeader(&b, format, osName, blueprintFile)
	writeHelpers(&b, format)
	writePrerequisites(&b, rules, osName)

	for i, rule := range rules {
		writeRule(&b, rule, i+1, len(rules), format, osName)
	}

	b.WriteString("\n")
	writeFooter(&b, format)

	return b.String()
}

// toolNeeds scans rules to determine which tools need to be bootstrapped.
type toolNeeds struct {
	brew   bool // homebrew action OR install action on mac
	mise   bool
	asdf   bool
	ollama bool
}

func detectToolNeeds(rules []parser.Rule, osName string) toolNeeds {
	var t toolNeeds
	for _, r := range rules {
		switch r.Action {
		case "homebrew":
			t.brew = true
		case "install":
			if osName == "mac" {
				t.brew = true
			}
		case "mise":
			t.mise = true
			if osName == "mac" {
				t.brew = true // mise is installed via brew on mac
			}
		case "asdf":
			t.asdf = true
			if osName == "mac" {
				t.brew = true // asdf is installed via brew on mac
			}
		case "ollama":
			t.ollama = true
		}
	}
	return t
}

func writePrerequisites(b *strings.Builder, rules []parser.Rule, osName string) {
	needs := detectToolNeeds(rules, osName)
	if !needs.brew && !needs.mise && !needs.asdf && !needs.ollama {
		return
	}

	b.WriteString("# --- Prerequisites ---\n")

	if needs.brew {
		b.WriteString(`if ! command_exists brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [ -x /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
  elif [ -x /home/linuxbrew/.linuxbrew/bin/brew ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  fi
fi
`)
	}

	if needs.mise {
		if osName == "mac" {
			b.WriteString(`if ! command_exists mise; then
  brew install mise
fi
`)
		} else {
			b.WriteString(`if ! command_exists mise; then
  mkdir -p "$HOME/.local/bin"
  curl -fsSL https://mise.run | sh
fi
export PATH="$HOME/.local/bin:$PATH"
`)
		}
	}

	if needs.asdf {
		if osName == "mac" {
			b.WriteString(`if ! command_exists asdf; then
  brew install asdf
fi
`)
		} else {
			b.WriteString(`if ! command_exists asdf; then
  ASDF_ARCH="$(uname -m)"
  curl -fsSL "https://github.com/asdf-vm/asdf/releases/latest/download/asdf-linux-${ASDF_ARCH}.tar.gz" -o /tmp/asdf.tar.gz
  tar -xzf /tmp/asdf.tar.gz -C /tmp
  sudo cp /tmp/asdf /usr/local/bin/asdf && sudo chmod 755 /usr/local/bin/asdf
  rm -f /tmp/asdf.tar.gz /tmp/asdf
fi
`)
		}
	}

	if needs.ollama {
		b.WriteString(`if ! command_exists ollama; then
  curl -fsSL https://ollama.com/install.sh | sh
fi
`)
	}

	b.WriteString("\n")
}

func writeHeader(b *strings.Builder, format, osName, blueprintFile string) {
	if format == "sh" {
		b.WriteString("#!/bin/sh\n")
	} else {
		b.WriteString("#!/bin/bash\n")
	}

	b.WriteString("#\n")
	b.WriteString(fmt.Sprintf("# Generated by blueprint export\n"))
	b.WriteString(fmt.Sprintf("# Blueprint: %s\n", blueprintFile))
	b.WriteString(fmt.Sprintf("# OS: %s\n", osName))
	b.WriteString(fmt.Sprintf("# Date: %s\n", time.Now().Format("2006-01-02")))
	b.WriteString("#\n\n")

	if format == "sh" {
		b.WriteString("set -eu\n\n")
	} else {
		b.WriteString("set -euo pipefail\n\n")
	}
}

func writeHelpers(b *strings.Builder, _ string) {
	b.WriteString("# --- Helpers ---\n")
	b.WriteString("command_exists() { command -v \"$1\" >/dev/null 2>&1; }\n")
	b.WriteString("\n")
}

func writeRule(b *strings.Builder, rule parser.Rule, index, total int, format, osName string) {
	def := handlerskg.GetAction(rule.Action)

	// Build summary line
	summary := rule.Action
	if def != nil && def.Summary != nil {
		summary = def.Summary(rule)
	}

	b.WriteString(fmt.Sprintf("# [%d/%d] %s: %s\n", index, total, rule.Action, summary))

	// Check if this action has a shell export function
	if def == nil || def.ShellExport == nil {
		b.WriteString(fmt.Sprintf("# SKIP: %s cannot be exported as shell.\n", rule.Action))
		if rule.Action == "decrypt" {
			b.WriteString(fmt.Sprintf("#   Uses blueprint's built-in AES-256-GCM decryption.\n"))
			if rule.ID != "" {
				b.WriteString(fmt.Sprintf("#   Run: blueprint apply <file> --only %s\n", rule.ID))
			}
		}
		if rule.Action == "authorized_keys" && rule.AuthorizedKeysEncrypted != "" {
			b.WriteString(fmt.Sprintf("#   Uses encrypted key file requiring blueprint decrypt.\n"))
			if rule.ID != "" {
				b.WriteString(fmt.Sprintf("#   Run: blueprint apply <file> --only %s\n", rule.ID))
			}
		}
		b.WriteString("\n")
		return
	}

	lines := def.ShellExport(rule, format, osName)
	if lines == nil {
		b.WriteString(fmt.Sprintf("# SKIP: %s cannot be exported as shell.\n", rule.Action))
		b.WriteString("\n")
		return
	}

	for _, line := range lines {
		b.WriteString(line + "\n")
	}
	b.WriteString("\n")
}

func writeFooter(b *strings.Builder, _ string) {
	b.WriteString("echo \"Done.\"\n")
}
